#!/bin/sh
rm *.o
rm kage.exe
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/data/point.cpp -o kage/data/point.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/data/color.cpp -o kage/data/color.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/data/strokecolor.cpp -o kage/data/strokecolor.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/data/vectordata.cpp -o kage/data/vectordata.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/timeline/frame.cpp -o kage/timeline/frame.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/timeline/framemanager.cpp -o kage/timeline/framemanager.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/timeline/framesmanager.cpp -o kage/timeline/framesmanager.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/timeline/layermanager.cpp -o kage/timeline/layermanager.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/stage.cpp -o kage/stage.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage/vectordatamanager.cpp -o kage/vectordatamanager.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors kage.cpp -o kage.o
g++ -c -I./ `pkg-config gtkmm-3.0 --cflags | sed 's/ -I/ -isystem /g'` -std=gnu++11 -fmax-errors=5 -Wfatal-errors main.cpp -o main.o
windres kage.rc -O coff -o kage.res
g++ ./kage/data/point.o ./kage/data/color.o ./kage/data/strokecolor.o ./kage/data/vectordata.o ./kage/timeline/frame.o ./kage/timeline/framemanager.o ./kage/timeline/framesmanager.o ./kage/timeline/layermanager.o ./kage/stage.o ./kage/vectordatamanager.o kage_gtkmm3.o main.o kage.res -o kage `pkg-config gtkmm-3.0 --libs | sed 's/ -I/ -isystem /g'`
