#!/bin/sh
rm *_gtkmm3.o
rm kage_gtkmm3.exe
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/data/point_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/data/color_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/data/strokecolor_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/data/vectordata_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/timeline/frame_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/timeline/framemanager_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/timeline/framesmanager_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/timeline/layermanager_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/vectordatamanager_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "./kage/stage_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "kage_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -std=gnu++11 -fmax-errors=3 -Wall -c "main_gtkmm3.cpp"  -I. $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
g++ -Wall "point_gtkmm3.o" \
"./color_gtkmm3.o" \
"./strokecolor_gtkmm3.o" \
"./vectordata_gtkmm3.o" \
"./vectordatamanager_gtkmm3.o" \
"./frame_gtkmm3.o" \
"./framemanager_gtkmm3.o" \
"./framesmanager_gtkmm3.o" \
"./layermanager_gtkmm3.o" \
"./stage_gtkmm3.o" \
"./kage_gtkmm3.o" \
"./main_gtkmm3.o" \
-o "kage_gtkmm3.exe" $(pkg-config gtkmm-3.0 --cflags --libs | sed 's/ -I/ -isystem /g')
