#!/bin/sh
set -e

# Register MIME type
if [ "$1" = "configure" ] && [ -x "`which update-mime-database 2>/dev/null`" ]; then
	update-mime-database /usr/local/share/mime
fi

# Register application
if [ "$1" = "configure" ] && [ -x "`which update-desktop-database 2>/dev/null`" ]; then
	update-desktop-database
fi
