name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install make libgtkmm-3.0-dev build-essential

    - name: Run check
      run: cd studio; make -f Makefile.gnu resource

    - name: Run distcheck
      run: make -f Makefile.gnu
