name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install make libgtkmm-3.0-dev build-essential

    - name: Create Resources
      run: cd studio; make -f Makefile.gnu resource

    - name: Create Binary
      run: cd studio; make -f Makefile.gnu
